version: 2.1 #circleci version
orbs:
  node: circleci/node@5.1.0
jobs: 
  run_tests:  #job name
    docker:
      - image: cimg/node:19.8.1
      - image: circleci/mongo:4.0-xenial-ram
    steps: 
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: run tests
          command: npm test
      - persist_to_workspace:
          root: ~/studious
          paths:
            - .
workflows:
  run_test_workflow:
    jobs: 
      - run_tests