version: 2.1 #circleci version
orbs:
  node: circleci/node@5.1.0
jobs: 
  run_tests:  #job name
    executor: node/default
    steps: 
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: run tests
          command: npm test
      - persist_to_workspace:
          root: ~/studious
          paths:
            - .
workflows:
  run_test_workflow:
    jobs: 
      - run_tests

